# =========================
# PROJECT CONFIGURATION
# =========================

data:
  dir: data
  files:
    transactions: transactions.csv
    labels: fraud_labels.csv
    users: users.json
    cards: cards.json
    merchants: merchant.json

preprocess:
  target: fraud_label
  datetime_col: tx_datetime
  id_cols: [transaction_id, card_id, client_id, merchant_id]
  drop_cols: []
  categorical: []
  numerical: []
  scale: true
  encode: true

split:
  test_size: 0.15
  val_size: 0.15
  random_state: 42
  stratify: true

imbalance:
  ml:
    use_smote: true
    smote_k_neighbors: 5
  gnn:
    normal_sample_ratio: 0.2

gnn:
  node_type: card
  edges:
    by_client: true
    by_merchant: true
    time_window_minutes: 30
  features:
    node_features: [amount, amount_log1p, credit_limit]

models:
  lr:
    max_iter: 1000
    class_weight: balanced
  rf:
    n_estimators: 300
    class_weight: balanced_subsample
    random_state: 42
  autoencoder:
    latent_dim: 32
    hidden: [128, 64]
    lr: 0.001
    epochs: 20
    batch_size: 512
    seed: 42
  gcn:
    hidden: 64
    lr: 0.001
    dropout: 0.2
    weight_decay: 0.0
    epochs: 30
    seed: 42
    class_weight: [1.0, 1.0]
  gat:
    hidden: 64
    lr: 0.001
    dropout: 0.2
    weight_decay: 0.0
    epochs: 30
    seed: 42
    class_weight: [1.0, 1.0]
  gin:
    hidden: 64
    lr: 0.001
    dropout: 0.2
    weight_decay: 0.0
    epochs: 30
    seed: 42
    class_weight: [1.0, 1.0]

artifacts:
  dir: artifacts
  save_transformers: true
